eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enabled: true
        serviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8881
#以下配置是避免 http://localhost:8881/refresh 需要权限问题
management:
  security:
    enabled: false
